### ISSUE TITLE
Add yourself as copyright holder

### ISSUE THREAD

**Issue by manphiz** [Wilfred/bison-mode#15]
Hi Wilfred,

I'm working on packaging bison-mode in Debian and when working on the copyright part the team notices that you are not part of the copyright holders (as listed in the comments).  As for the current status the common practice is to just include the ones in the copyright notice, I would have to leave you out for now.  Would you like to add yourself there as well so that we can acknowledge your contributions in our copyright file?

**Comment by Wilfred** [comment]
@manphiz I've only lightly patched this module, I'm not terribly actively maintaining it and don't feel the need for copyright assignment.

I'm happy to add myself if it makes your life easier, but otherwise no objections to the current setup :)
