### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nicolasbock** [Wilfred/bison-mode#7]
Hi Wilfred,

I would like to package your bison-mode for Gentoo. What's the license your mode is released under?

Thanks,

nick

**Comment by Wilfred** [comment]
Hi Nicolas!

It's GPL, see the header: https://github.com/Wilfred/bison-mode/blob/master/bison-mode.el#L10

Let me know if you have any other issues :)

**Comment by nicolasbock** [comment]
Thanks!
