### ISSUE TITLE
File mode specification error

### ISSUE THREAD

**Issue by ricardoamaro** [Wilfred/bison-mode#9]
Getting the following error on Emacs 25.2:
(emacs --debug-init)
```
File mode specification error: (error There should be a mode declaration in /usr/share/emacs/25.2/etc/srecode/c.srt)
```

**Comment by Wilfred** [comment]
Why do you think this is bison-mode? Do you have a full traceback? How can I reproduce this?

**Comment by ricardoamaro** [comment]
Thanks for the quick reply @Wilfred .
Turns out that this is seems to be an error not related to bison-mode.
